version: 2
references:
    container_config: &container_config
        environment:
            IMAGE_NAME: gnuton/vitasdk-docker
            DOCKER_TAG: $(date +%Y%m%d)
        docker:
            - {image: 'circleci/buildpack-deps:stretch'}
jobs:
    build:
        <<: *container_config
        steps:
            - checkout
            - setup_remote_docker
            - {run: {name: 'Build Docker image', command: 'docker build -t $IMAGE_NAME:latest .'}}
    publish:
        <<: *container_config
        steps:
            - setup_remote_docker
            - {run: {name: 'Publish Docker Latest Image to Docker Hub', command: "echo \"$DOCKERHUB_PASS\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin\ndocker push $IMAGE_NAME:latest\n"}}
            - {run: {name: 'Publish Docker Tagged Image to Docker Hub', command: "echo \"$DOCKERHUB_PASS\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin\ndocker push $IMAGE_NAME:$DOCKER_TAG\n"}}
              
workflows:
    version: 2
    build-master:
        jobs:
            - {build: {filters: {branches: {only: master}}}}
            - {publish: {requires: [build], filters: {branches: {only: master}}}}
    build-master-nightly:
        jobs:
            - {build: {filters: {branches: {only: master}}}}
            - {publish: {requires: [build], filters: {branches: {only: master}}}}
        triggers:
            - {schedule: {cron: '0 0 * * *', filters: {branches: {only: master}}}}

